### ISSUE TITLE
Support updated SELFDESTRUCT operation in Cancun

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#521]
With the [Cancun](https://www.evm.codes/?fork=cancun) revision the semantic of the SELFDESTRUCT instruction has changed. In particular, accounts only may self-destruct if they have been created in the same transaction (see [EIP-6780](https://eips.ethereum.org/EIPS/eip-6780)).

**Comment by simonlechner** [comment]
This issue was fixed in #561.
