### ISSUE TITLE
LFVM: Memory expansion overflow checks

### ISSUE THREAD

**Issue by simonlechner** [Fantom-foundation/Tosca#524]
During the changes required for the limiting of the init code size in #498 an issue regarding the memory expansion calculation has been detected. The [toValidMemorySize](https://github.com/Fantom-foundation/Tosca/blob/2715eec8f7fffce39ac7817623fa492071f79900/go/vm/lfvm/memory.go#L31) overflows without any warning or error.

To close this issue it has to be fixed in the LFVM code and investigated why the CT did not produce such an error case.

**Comment by HerbertJordan** [comment]
A similar issue was discovered in the CT specification itself recently, and was addressed by #517.

In particular, see this [comment](https://github.com/Fantom-foundation/Tosca/pull/517#discussion_r1633333850).

**Comment by LuisPH3** [comment]
This issue affects as well   #541, where a unit test supposed to fail was not. 
This ticket has a more interesting take on this issue, why did the CT not find this issue? 
In order to reproduce the issue, revert #541 changes for go/vm/lfvm/memory.go
