### ISSUE TITLE
Analyse and document LFVM memory usage

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#673]
To ensure operational safety, the memory consumption of the LFVM should be investigated and, if necessary, evaluated for needed restriction methods.

Particular focus should be on:
- [x] memory usage of the code conversion cache
- [x] memory usage of the code conversion process (risk for high memory usage due to malicious input data)
- [x] memory usage of the hash caches
- [x] memory usage of EVM memory
- [x] memory usage of EVM stacks
- [x] memory usage in instruction implementations
- [x] memory usage of interpreter

The result should be a list of tasks improving and/or restricting worst-case memory usage of the investigated components.

**Comment by HerbertJordan** [comment]
The memory usage estimate for cached codes is currently off by a factor of 4. It assumes each instruction to require a single byte while in reality it consumes 4.

**Comment by simonlechner** [comment]
> The memory usage estimate for cached codes is currently off by a factor of 4. It assumes each instruction to require a single byte while in reality it consumes 4.

In the long format an instruction is composed of a uint16 for the instruction and another uint16 for the optional data argument.

**Comment by simonlechner** [comment]
**Memory usage of code conversion cache**
Cache size is set to 1GB and can not be changed when using the `NewInterpreter` function.
The lru cache does not use an evict buffer. The size enforcement has been checked using cache stress tests.

**Memory usage of conversion process**
There are no buffers used during the conversion process. The long format version of the code has at most as many instructions as the original code. Each instruction is 4 times the size of the original ones. 

**Memory consumption of hash cache**
Cache for both 32 and 64 byte inputs, the size is set individually to 1<<16 and 1<<18 respectively. These values are hard coded in the go code and can not be changed without altering the code. The size enforcement has been checked by looking at the memory consumption while running a test hashing random 32 and 64 byte input values over a 30 minute period.

**Memory usage of EVM Memory**
It is only possible to resize memory through the `getSlice` function which includes the gas billing for any possible memory expansion. Further an upper bound called `maxMemoryExpansionSize` is taken from geth.

**Memory usage of EVM Stack**
Each stack is an array of size 1024 and type uint256.Int. Stacks are reused using a `sync.Pool` which handles the number of objects dynamically. Go’s sync.Pool does not offer the functionality of setting an upper limit but running 10000 concurrent calls has shown not to be a problem regarding the memory consumption.

**Memory usage of Instruction Implementations**
Instructions do not use buffers, memory is not copied but slices are used to point to data in memory. Except for the log operations which copy the log data from memory to the log’s data field but gas depending on the log data size is charged for these operations.

**Memory usage of Interpreter**
The size of the input is not checked or metered in the interpreter but each byte of the input is billed in the processor. Code and init code size are both metered and limited by upper bounds taken from geth.
