### ISSUE TITLE
Review static code analysis infrastructure for the LFVM code base

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#675]
A number of static code analysis tools are currently enabled on the Tosca repository. For those, it should be checked:

- [x] are they up-to-date or could they be updated
- [x] are they enabled for the LFVM code base
- [x] are there any issues reported by them need to be fixed

**Comment by simonlechner** [comment]
Updated in #919.
Covering the whole go codebase in each PR, therefore also covering the main branch.
No issues reported.
