### ISSUE TITLE
Add fuzzing tests to code conversion code

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#679]
The code conversion in the LFVM code base is one of the biggest surfaces for attackers to crash the LFVM interpreter. Thus, extra care should be applied to harden this target against attacks.

One contribution to this is the establishment of a fuzzer test for input codes in an attempt to identify implementation issues in the fuzzer that could lead to crashes.

**Comment by LuisPH3** [comment]
Implementation: #717

**Comment by simonlechner** [comment]
Converter fuzzing is running on [jenkins](https://scala.fantom.network/job/Tosca/job/Fuzzing-Test-LFVM-converter/).
