### ISSUE TITLE
Establish full-mode CT run targeting the LFVM as a daily/weekly test

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#691]
The current conformance test in Jenkins is only running in non-full mode. For full coverage, a new pipeline should be created, running the CT tests in full mode targeting the LFVM configuration selected for the release.

Todo:

- [x] identify LFVM configuration to be released (see #676)
- [x] make sure that the CT driver is using this configuration when selecting LFVM as the test target
- [x] prepare a Jenkins script in LaScala for running the full CT test with code coverage reporting
- [x] arrange the periodic execution of this test pipeline on Jenkins with the LaScala team
- [x] integrate this full CT testing run into the LaScala's release candidate testing

**Comment by simonlechner** [comment]
LFVM release version is fixed
It is only possible to get the production version without workarounds
CT jenkins scripts are updated
Depending on the interpreter it is executed different number of times.
