### ISSUE TITLE
Recheck the configuration of Tosca's daily LFVM Verification job on Jenkins

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#692]
Right now, a [daily evaluation](https://scala.fantom.network/job/Tosca/job/Validate-LFVM/) run of the LFVM implementation is executed on Jenkins. For this, it should be checked that

- [ ] it uses the LFVM configuration to be released (see #676)
- [ ] this pipeline is part of LaScala's release candidate testing

**Comment by LuisPH3** [comment]
FYI: https://github.com/Fantom-foundation/LaScala/pull/159 bumps up go toolchain version to 1.22.
Once this PR is merged, we should update requirements for Tosca: update BUILD.md and re-check pipelines.

**Comment by Lubomir-Jahn** [comment]
FYI: this https://github.com/Fantom-foundation/LaScala/pull/159 has been just merged
