### ISSUE TITLE
Develop stress tests for the LFVM interpreter

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#694]
In order to understand LFVM's behavior under high-load situations stress tests should be developed and carried out. In particular, the following scenarios are of interest:

- [x] a high number of concurrent EVM executions for small transactions (10.000 parallel runs)
- [x] a high number of (parallel) calls targeting distinct codes (ineffective cashing of codes)
- [x] a high number of (parallel) calls with large codes
- [ ] a high number of parallel calls stressing the hash cache

**Comment by simonlechner** [comment]
Solved with #926.
