### ISSUE TITLE
Benchmark of LFVM performance

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#695]
Before the release, a sanity check of LFVM's performance should be conducted. To that end, the following benchmarks should be carried out and the results analysed:

- [x] the micro benchmarks in the Tosca repository
- [x] the block-sync performance using `aida-vm-sdb` for the full block range using an in-memory DB

Results should be contrasted with alternative EVM implementations (including Geth 1.14).

**Comment by facuMH** [comment]
This char contains results of running micro benchmarks on main branch of 29.10, performance relative to geth.

![Benchmark runtime relative to geth](https://github.com/user-attachments/assets/184c1970-b06d-4f09-acac-a94979aca08c)

**Comment by simonlechner** [comment]
Throughput when running the fantom mainnet history up to block 20M 
![Fantom Mainnet history](https://github.com/user-attachments/assets/9e5414a1-52aa-46b6-ac42-a8ffcd333ef6)

**Comment by simonlechner** [comment]
The performance of LFVM is still in the expected range.
