### ISSUE TITLE
Check skipped CT tests for LFVM

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#739]
When running CT on LFVM the final reports lists a number of skipped tests:

![Image](https://github.com/user-attachments/assets/f94b968f-b090-49c5-abf0-7a569658dfd6)

In this case, 57 tests got skipped and 6363756 had an unsupported revision.

It needs to be checked whether those tests are still skipped for a good reason. Also, there should no longer be an unsupported revision for LFVM.

**Comment by simonlechner** [comment]
All skipped tests are due to states with program counters on data.
There are cases with unsupported revisions because of the rule `unknown_revision_is_end`, which produces states with a revision larger than the newest supported one.
