### ISSUE TITLE
Evaluate option for EVM compatible OpCodes in LFVM

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#750]
To simplify code conversion and to reduce overall code size, an idea would be to reuse the same op-code values for LFVM as they are defined for the EVM in general.

What needs to be investigated:
- [x] impact on code base; will anticipated effects actually materialize?
- [x] impact on LFVM performance

**Comment by LuisPH3** [comment]
Work completed by #748 
- comparable performance
- binary compatible opcodes (for not lfvm exteded opcodes)
