### ISSUE TITLE
Comprehensive unit testing of LFVM operations

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#751]
This task focuses on testing properties of VM instructions, in particular code in `instructions.go` and `super_instructions.go` 

Common properties to opcodes are: 
- minimum required version
- static mode violation
- dynamic cost computation, leading to out of gas or overflow
- context calls are issued.

Properties common to certain ops are: 
- JUMPDEST check for any jump operation (except for JUMP_TO) 
    - [x] TestInstructions_JumpInstructionsCheckJUMPDEST
- EIP-2929 COLD/WARM dynamic cost introduced in Berlin
     - SLOAD, 
     - SSTORE
     - *CALL, 
     - BALANCE, 
     - EXT*
     - SELFDESTRUCT 
- Memory operations
...

**Comment by LuisPH3** [comment]
Attempt to refactor existing end-to-end test  #753

**Comment by LuisPH3** [comment]
- [ ] minimum required version
- [ ] static mode violation 
- [ ] dynamic cost
- [ ] context calls are issued.

**Comment by LuisPH3** [comment]
note: opSwap2_Swap1_Pop_Jump never checked for jumpdest and is never tested for it.

**Comment by facuMH** [comment]
After the merge of #837 #839 #841 #838 there should be still need to test specific branches of
- Calldataload
- opExp
- opExtcodehash
- opExtCodeCopy
- returndatacopy

**Comment by facuMH** [comment]
- opLog also needs a test for memory expansion

**Comment by LuisPH3** [comment]
Regarding context calls, It would be interesting not only to test that calls are issued, but that the arguments passed to external context calls are correct as well:

- [x] AccessAccount
    - TestSelfDestruct_ExistingAccountToNewBeneficiary
- [x] Balance
    - TestSelfDestruct_ExistingAccountToNewBeneficiary
- [ ] GetCodeSize
- [ ] GetCode
- [x] AccountExists
     - TestSelfDestruct_ProperlyReportsNotEnoughGas
- [ ] AccessStorage
- [ ] GetStorage
- [ ] SetStorage
- [ ] Call
- [ ] EmitLog #856 
- [x] SelfDestruct
     - TestSelfDestruct_ExistingAccountToNewBeneficiary
- [ ] GetTransientStorage
- [ ] SetTransientStorage
