### ISSUE TITLE
Remove internal redundancy of error propagation and status

### ISSUE THREAD

**Issue by facuMH** [Fantom-foundation/Tosca#758]
in memory expansion function status is changed according to the corresponding error, and also an error is returned, callers of this function then have nothing to do with said error since changing status could override the previously assigned status. 
This should be modified so that all errors are only propagated (not modifying context stastus) in internal functions, and only high level functions deal with context status based on propagated errors.

**Comment by facuMH** [comment]
PRs that contribute to this issue are: #795 #797 #790 #786 #783 #779 #772 #775

**Comment by LuisPH3** [comment]
- [ ] fix problem detected by logger changes:  differentiate logic errors / runtime errors  (the valid failure states vs the vm runtime errors)
